### ISSUE TITLE
Connection fails

### ISSUE THREAD

**Issue by olleolleolle** [NOX73/celluloid-http#2]
Perhaps the README forgot to tell me something, but I am getting all-the-way-down-to-C errors when trying to do a GET request to a URL.

``` rb
Celluloid::Http.get "http://ollehost.dk"  # is the shortest failing reproduce.
```

```
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/reactor.rb:43: [BUG] Segmentation fault
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.3.0]

-- Control frame information -----------------------------------------------
c:0017 p:0207 s:0072 b:0070 l:000069 d:000069 METHOD /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/reactor.rb:43
c:0016 p:0015 s:0064 b:0064 l:000063 d:000063 METHOD /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/reactor.rb:26
c:0015 p:0092 s:0060 b:0060 l:000059 d:000059 METHOD /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io.rb:42
c:0014 p:0020 s:0055 b:0055 l:000054 d:000054 METHOD /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/stream.rb:42
c:0013 p:0031 s:0052 b:0052 l:000048 d:000051 BLOCK  /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/tcp_socket.rb:87
c:0012 p:0459 s:0049 b:0049 l:000048 d:000048 METHOD /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/tcp_socket.rb:84
c:0011 p:---- s:0040 b:0040 l:000039 d:000039 FINISH
c:0010 p:---- s:0038 b:0038 l:000037 d:000037 CFUNC  :new
c:0009 p:0025 s:0033 b:0033 l:000032 d:000032 METHOD /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-http-0.0.5/lib/celluloid-http/connection.rb:6
c:0008 p:---- s:0028 b:0028 l:000027 d:000027 FINISH
c:0007 p:---- s:0026 b:0026 l:000025 d:000025 CFUNC  :public_send
c:0006 p:0021 s:0020 b:0020 l:000019 d:000019 METHOD /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/calls.rb:11
c:0005 p:0039 s:0013 b:0013 l:000012 d:000012 METHOD /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/calls.rb:63
c:0004 p:0014 s:0007 b:0007 l:000260 d:000006 BLOCK  /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/actor.rb:326
c:0003 p:0135 s:0005 b:0005 l:0004f8 d:000004 BLOCK  /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/tasks/task_fiber.rb:28
c:0002 p:---- s:0003 b:0003 l:000002 d:000002 FINISH
c:0001 p:---- s:0001 b:-001 l:000000 d:000000 ------

-- Ruby level backtrace information ----------------------------------------
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/tasks/task_fiber.rb:28:in `block in initialize'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/actor.rb:326:in `block in handle_message'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/calls.rb:63:in `dispatch'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/calls.rb:11:in `dispatch'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid/calls.rb:11:in `public_send'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-http-0.0.5/lib/celluloid-http/connection.rb:6:in `open'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-http-0.0.5/lib/celluloid-http/connection.rb:6:in `new'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/tcp_socket.rb:84:in `initialize'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/tcp_socket.rb:87:in `rescue in initialize'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/stream.rb:42:in `wait_writable'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io.rb:42:in `wait_writable'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/reactor.rb:26:in `wait_writable'
/Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-io-0.13.1/lib/celluloid/io/reactor.rb:43:in `wait'
```
- /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-http-0.0.5/lib/celluloid-http.rb
- /Users/olle/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/celluloid-0.13.0/lib/celluloid.rb
- https://gist.github.com/olleolleolle/f393da46dba538733cf6

**Comment by NOX73** [comment]
Can't reproduce it. 

``` rb
1.9.3p194 :001 > require 'celluloid-http'
 => true
1.9.3p194 :002 > Celluloid::Http.get "http://ollehost.dk"
 => #<Celluloid::Http::Response:0x007fe0648cb198 @body="<!DOCTYPE html>\n<html lang=\"en\">\n<head profile=\"http://www.w3.org/2005/10/profile\">\n<title>Ollehost: Document motel</title>\n<link href=\"/css/orange.css\" rel=\"stylesheet\" media=\"screen\" type=\"text/css\">\n<link rel=\"icon\" type=\"image/x-icon\" href=\"/favicon.ico\" >\n</head>\n\n<body class=\"first\">\n\n<h1>Ollehost: Document motel</h1>\n<p>I am <a href=\"http://github.com/olleolleolle\" title=\"GitHub\nprofile\">Olle Jonsson</a>, and I write a personal <a\nhref=\"blog/\">blog</a>. This is the thin center of my web presence. </p>\n\n<p>\nWere you looking for my <a href=\"http://www.olleolleolle.dk/\" title=\"Olleolleolle: Internet contractor\">software consultant web page</a>?\n</p>\n\n<p>\nExperiments: <a href=/live/>Video archive</a>.\n</p>\n\n</body></html>\n", @headers={"Date"=>"Fri, 19 Apr 2013 10:25:26 GMT", "Server"=>"Apache/2.2.16 (Debian)", "Last-Modified"=>"Fri, 25 May 2012 16:13:50 GMT", "ETag"=>"\"15ee6f3-2df-4c0dea75ceb80\"", "Accept-Ranges"=>"bytes", "Content-Length"=>"735", "Content-Type"=>"text/html"}, @status=nil, @finished=true, @parser=#<HTTP::Parser:0x007fe0648caab8>>
1.9.3p194 :003 >
```

What versions of gems do you use? Could you create a gemset, install only `celluloid-http` gem and try again?

**Comment by halorgium** [comment]
I think this is a bug with `nio4r`: tarcieri/nio4r#24

**Comment by halorgium** [comment]
As a best practice, it would be good to depend on `celluloid-io >= 0.14.0`. This has the dependency on `nio4r` which has the bugfix.
